---
os: linux
dist: bionic

language: node_js
node_js:
  - "lts/*"

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb
  - npm install
  - gem install html-proofer

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - hugo version
  - hugo --minify --i18n-warnings
  - htmlproofer ${TRAVIS_BUILD_DIR}/public/ --allow-hash-href --url-ignore "/moodlebox.home/,/stats.martignoni.net/" || true

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete ${TRAVIS_BUILD_DIR}/public/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master

env:
  jobs:
    - PRODUCTION=true
  global:
    - HUGO_RELEASE=0.76.5
    - secure: BH+L9P6vwcN+CcKicMY9LnrDfQ6UiBcvAVhKO9djb1iSpI863ZBm6NptxTagXXYpWMbK2CQEb5sI83tECEbAaD6Lh1QdIeKmt+XP16kswJtn09mEs1599h14r15+qufyf995h6F4PByHl+NzYV0mZ4jqdDlZ007z0zc3lg2O2r9gKsgwc9OvJCmddeINtepg3fwoLYrAnID9aUnerPzQgrI8gUzwOeurtD0AZnoKdca83gikGntNnCxc/PvzPVlA98kqRG9/TmLXmzFj2xkjov8e53+tUBrJUUfnQ4ORvmkx9SFcY8mjo7Q0e9KC5oTNi4w4HLhfQsu0rBVWiaMnQKVP5K9r9h0hdDPtHXI1+ead5jWdFsgu5h81c6AnaOT+kT4nXVCiE1Ys3ZUAkffq8NnFBbKlPsDJAQ3ZW7wxATHB2dTkUkPkKVtVJ397muHNGHMauPY8dSLlNErTrFzk00GkCg+FqsrQr0olugLGRCa/hkdqauiruOP4hQH+COfugkepVHQMOIdgEPcRUM1p67L1nadz9ZQVkhv5BtIhVRezLITHOr5pA4oCYPeIdIvmyi42N8xKrqJUVPyq/KK30rjXNTxomaZC7nbJhDMZBw5P1hL1GiL0Mv63Sc5QSWpR5TmEWRN4kNf93A0RduRfrJNYSeZFElJ1qVMjEclF7N4=
    - secure: UJOs6wEKE0M9kAAjhSrjUcT5URSnPRLwj3JeMggfS0a4fnSUq9d63Ho62r/eV/peup0NAA8MKBy2g2pykrAUnmiCDvB6ajbuPApoyGhnmVwweT3mGMCwOBWEOHECiesadnN3sm1n6Y+AmN8Ablg540yfmSYRYRkEdPUZhfQeT6XOAXQrtvaXoH3GXF/9EnHVs+fU0Q+U05P3O6bXpdwbE+BwF6bOQY/EXHF3QhRIoAsT2fywVcAF6MRpqFu1Rqyddpv0exMZHoppNIhhk7HUdUP972a1zo5Q9N+PHO8ufPOxzyJeALWb4TiSut/EOL+ogBEIZLg/fGKnrHgb2mn8Wfdim/7+dtYx0miOHL27hoF67U1/VgMHYp+jAhpRZKnHkQvDb/MGiXH1gyKCJ7MnLCSpc9g6Mvnb1gh9nFymcAA39LMmE5qf63RHf57J6wqs6LANGlMF7h2VITdiUyfIHHGvpjibdAVor2g4a7/Pgf9Tt52YAAdQzifHCufNx98umjsdecadHJa0RvsbcjHLmXxubs83yVtm7CTK7ZaJ151ClhjFedpPemTCVAdithHUIaZVlhTKEXA4LiQGMPcIdDGkeDSHWIrIfnBJwL+M4Ce5QAj7zpJQ4xoT3FafrbaxWHZTtAtf8mM82TLRPUEmLwaCYFtM9rAXCQibwVhHavs=
    - secure: ukcSTHNOeVvXtCTpD0k/8QhkgUZg/Mfmc5itUl77XOY4cHJHRNvDtDyfD+oNzxMQXx226LadyY2Is2QlR6nfU0vFR0FgVvqiNCIsevPKXWF1Xd0/XewbCBDzJYeqtAwt8KcG8aKOt74px5Bmazn3yGmuu1z/idZ232fqoapkg4/BoPk4/BmWRDZ6lKY2ktiMY0o3kGdXykbb5T/C0lNDAwJhD9oFpR+8JHchYunC/ZccEMBBIwOt1qQof92qjchaMQWHFMRsRiyRDFzqtsZttMqxNgK7QoMU5hQIBA56RtY6nfzjRpLOlDqJ3YjE6tU1ky3vzYgSxlFsuKK6pbDKdNiUETkmc2zPl3QSczkU1fHd3X4PMejRn3Ug0KMwkqXh9elDZzmElC75/RgYLzSDvwgHmD+pMFlvp4LEWJIboNuowIddS8OdcMRkHBi4gyNOxdSFsilRWd6LwuchiPwwc0SyiWNnmJKwEUPoOayakS0jYfhRe/LEyUBTTa+5mBA+C0pLFv56UinNMerRWQ9ckshwpeO4y1oFsk4Icfj1ezxKCkvGHG5kMrVt40UJ6LXiWheP+CDWuW2boU2iJ7OZXsq1TFKIg9XFlhtsfbk033+slsv3/YCOTe5D2k2Hum2Fbj+3Rr+ar01lxNK68AHi9fFPjl2GRNiU5lhDiwheayw=

cache:
  directories:
    - node_modules
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

notifications:
  email:
    on_success: never
