name: Hugo CI & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  HUGO_RELEASE: '0.76.5'
  SERVER: production
  DEPLOY_USER: blabla
  DEPLOY_HOST: blublu
  DEPLOY_DIRECTORY: bloblo

jobs:

  build:
    name: Build with Hugo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_RELEASE }}
          extended: true
      - name: Check Hugo installation
        run: hugo env
      - name: Build website
        run: hugo --minify --i18n-warnings

  deploy:
    name: Deploy to web server with rsync
    runs-on: ubuntu-latest
    steps:
      - name: List directory content
        run: ls -l
      - name: Check rsync
        run: rsync --version
