name: Hugo CI & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SERVER: production

jobs:
  build:
    name: Build and deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_RELEASE }}
          extended: true
        env:
          HUGO_RELEASE: '0.76.5'
      - name: Check Hugo installation
        run: hugo env
      - name: Build website
        run: hugo --minify --i18n-warnings
      - name: Deploy via rsync
        uses: pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzr --delete'
          src: 'public/'
          dest: '${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/home/${{ secrets.DEPLOY_USER }}/ghdeploytest/'
#          - ${{ secret.DEPLOY_DIRECTORY }}
