name: Hugo CI & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  HUGO_RELEASE: '0.76.5'
  SERVER: production

jobs:
  build:
    name: Build with Hugo and deploy to web server with rsync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_RELEASE }}
          extended: true
      - name: Check Hugo installation
        run: hugo env
      - name: Build website
        run: hugo --minify --i18n-warnings
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: public/
          remote_path: /home/${{ secret.DEPLOY_USER }}/ghdeploytest/
#           remote_path: ${{ secret.DEPLOY_DIRECTORY }}
          remote_host: ${{ secret.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secret.DEPLOY_USER }}
          remote_key: ${{ secret.DEPLOY_KEY }}
