name: Hugo CI & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  HUGO_RELEASE: 0.76.5
  SERVER: production
  DEPLOY_USER: blabla
  DEPLOY_HOST: blublu
  DEPLOY_DIRECTORY: bloblo

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Hugo
        uses: jakejarvis/hugo-build-action@v${HUGO_RELEASE}
        with:
          args: --build-arg --minify --i18n-warnings
#       - name: Get Hugo deb package
#         uses: wei/wget@v1
#         with:
#           args: "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
#       - name: Install and get Hugo version
#         run: sudo dpkg -i hugo*.deb && hugo version && hugo env
