name: Hugo CI & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  HUGO_RELEASE: 0.76.5
  SERVER: production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: wget
      uses: wei/wget@v1
      with:
        args: "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
